USE adlister_db;

DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
  id       BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) UNIQUE  NOT NULL,
  email    VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(100)        NOT NULL,
  PRIMARY KEY (id)
);
